### ISSUE TITLE
Release Unit Converter Ultimate on F-Droid

### ISSUE THREAD

**Issue by ascuccaro** [physphil/UnitConverterUltimate#13]
[F-Droid](https://f-droid.org/) is an Android App Store exclusively for open source apps. See [F-Droid's Wikipedia page](https://en.wikipedia.org/wiki/F-Droid). You can browse the catalog of available apps on [Fossdroid](https://fossdroid.com/).

Users choosing to avoid Google's proprietary libraries and those with AOSP based ROMs find the F-Droid option very useful. So, I request Unit Converter Ultimate to be made available on the F-Droid store. 😃

**Comment by krt16s** [comment]
Ref: https://github.com/physphil/UnitConverterUltimate/issues/20

**Comment by pR0Ps** [comment]
Done, see https://gitlab.com/fdroid/fdroiddata/merge_requests/1779

**Comment by KrasnayaPloshchad** [comment]
You should also add a link to F-Droid with badge, you can get the badge from here:
https://f-droid.org/posts/get-it-on-f-droid-badges/

**Comment by est31** [comment]
Note that due to firebase I had to disable the 5.0 build. It would be great if you could add an f-droid gradle flavour so that future versions can be put on F-Droid again. Thanks!

**Comment by physphil** [comment]
Don't worry, I'm working on it! I have a PR waiting to create an fdroid flavour, I just wanted to focus on the 5.0 release and then it's my top priority.

**Comment by physphil** [comment]
I'm planning on having this implemented in version 5.1.  There will be a minor bug fix release before that, but afterwards I'm going to be focusing on this.

**Comment by physphil** [comment]
#30 Has been merged into `develop` with much help from @pR0Ps, which for the 5.1 release _should_ allow for building on fdroid once again.  It adds a `base` build flavour which should be void of any Googly-related things.  From what I understand the metadata file just needs to be updated to reference that new flavour.

Thanks again to you all for your help!

**Comment by KrasnayaPloshchad** [comment]
Now I can see the F-Droid link on README.md. Yay!

**Comment by est31** [comment]
@physphil that's awesome to hear! Please ping me via this issue when you do the 5.1 release so that I can update it on fdroiddata as fast as possible (otherwise it may get forgotten).

Little question: can you add `jcenter()` to the top level build.gradle? I'm running into an issue when trying to build the project, very similar to this one: http://stackoverflow.com/q/40826935

Also, I've got a build issue about casing of file names (probably not an issue on windows, but the buildserver runs on linux, and linux filesystems are case sensitive):

```
:app:compileBaseReleaseJavaWithJavac/home/vagrant/build/com.physphil.android.unitconverterultimate/app/src/main/java/com/physphil/android/unitconverterultimate/api/FixerAPi.java:26: error: class FixerApi is public, should be declared in a file named FixerApi.java
public class FixerApi {
       ^
/home/vagrant/build/com.physphil.android.unitconverterultimate/app/src/main/java/com/physphil/android/unitconverterultimate/ui/ScrollAwareFABBehaviour.java:30: error: class ScrollAwareFabBehaviour is public, should be declared in a file named ScrollAwareFabBehaviour.java
public class ScrollAwareFabBehaviour extends FloatingActionButton.Behavior {
       ^
Note: /home/vagrant/build/com.physphil.android.unitconverterultimate/app/src/main/java/com/physphil/android/unitconverterultimate/MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

```

otherwise I had no issues building, so I guess once the 5.1 release is there it can be built.

**Comment by physphil** [comment]
No problem! Do me a favour, can you create an issue on GitHub for jcenter
so it doesn't slip my mind?

Yeah I noticed that casting issue as well, I think it should be fixed in
develop now.

On Nov 27, 2016 1:01 PM, "est31" <notifications@github.com> wrote:

@physphil <https://github.com/physphil> that's awesome to hear! Please ping
me via this issue when you do the 5.1 release so that I can update it on
fdroiddata as fast as possible (otherwise it may get forgotten).

Little question: can you add jcenter() to the top level build.gradle? I'm
running into an issue when trying to build the project, very similar to
this one: http://stackoverflow.com/q/40826935

Also, I've got a build issue about casing of file names (probably not an
issue on windows, but the buildserver runs on linux, and linux filesystems
are case sensitive):

:app:compileBaseReleaseJavaWithJavac/home/vagrant/build/com.physphil.android.unitconverterultimate/app/src/main/java/com/physphil/android/unitconverterultimate/api/FixerAPi.java:26:
error: class FixerApi is public, should be declared in a file named
FixerApi.java
public class FixerApi {
       ^
/home/vagrant/build/com.physphil.android.unitconverterultimate/app/src/main/java/com/physphil/android/unitconverterultimate/ui/ScrollAwareFABBehaviour.java:30:
error: class ScrollAwareFabBehaviour is public, should be declared in
a file named ScrollAwareFabBehaviour.java
public class ScrollAwareFabBehaviour extends FloatingActionButton.Behavior {
       ^
Note: /home/vagrant/build/com.physphil.android.unitconverterultimate/app/src/main/java/com/physphil/android/unitconverterultimate/MainActivity.java
uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.


otherwise I had no issues building, so I guess once the 5.1 release is
there it can be built.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/physphil/UnitConverterUltimate/issues/13#issuecomment-263136673>,
or mute the thread

**Comment by physphil** [comment]
@est31 I've tagged the 5.1 release, let me know how it works out!

**Comment by est31** [comment]
The 5.1 release is pushed to git, the build should be available within the next 24 hours: https://gitlab.com/fdroid/fdroiddata/commit/d4a656e5

I've tried the build locally, and got no problems, so most likely it won't fail on the buildserver either.
